name: Mineback
version: 0.1
main: com.Mineback.plugin.Mineback
author: HanavanOnline
commands:
    mineback:
        description: Access the Mineback administrator commands
        usage: /mineback